### ISSUE TITLE
Generate all video HTML from one shortcode

### ISSUE THREAD

**Issue by mdlincoln** [cmu-lib/dhlg#12]
Currently the project video pages use this metadata structure:

```yaml
iframe: "<iframe width='970' height='546' src='//www.youtube.com/embed/r32qwAENWng' frameborder='0' allowfullscreen></iframe>"
#
# These video settings are totally optional. It's only purpose
# is SEO, so that videos show up in Google hopefully with a 
# thumbnail.
# More › https://developers.google.com/webmasters/videosearch/schema?hl=en&rd=1
#
# embedURL – A URL pointing to a player for the specific video.
# contentURL – A URL pointing to the actual video media file
# thumbnailUrl – A URL pointing to the video thumbnail image file.
#
video:
    embedURL: "https://www.youtube.com/embed/r32qwAENWng"
    contentURL: "http://www.youtube.com/watch?v=r32qwAENWng"
    thumbnailUrl: "http://img.youtube.com/vi/r32qwAENWng/0.jpg"
```

This makes the authors repeat a lot of info that should just be programmatically generated by entering the Youtube ID code (e.g. `r32qwAENWng`) exactly once in the yaml header.
